linters:
  enable:
    - govet
    - revive  
    - errcheck
    - staticcheck
    - gofmt
    - unused

  disable: [] 
output:
  formats:
    - format: colored-line-number

run:
  go: 1.23
  timeout: 2m

issues:
  exclude-dirs-use-default: true
  uniq-by-line: true
