[Zookeeper]
connection_url="127.0.0.1:2181"
connection_wait_time_ms=4000
session_timeout_ms=400000000000

[Server]
internal_grpc_addr=":8000"
exposed_grpc_addr=":8080"
client_grpc_addr=":8909"

[Topic]
replicas=3