[Zookeeper]
port=2181
connection_wait_time_ms=4000
session_timeout_ms=400000000000

[Server]
internal_grpc_addr=":8000"
exposed_grpc_addr=":8080"
client_grpc_addr=":8909"

[Topic]
replicas=3

[EventLoop]
max_fd_soft_limit=13824
task_queue_buffer_size=1000
kqueue_event_buffer_size=100
epoll_event_buffer_size=100
blocking_mode=true
write_time_space_ms=10
max_connection=1000
per_connection_buffer_size=1000

[AsyncTCP]
port=8790

[AsyncTaskQueue]
max_size=100