version: "3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg:Z

  app:
    build: ./docker/.
    container_name: my-app
    depends_on:
      - zookeeper