version: "3.8"

services:
  ripple-server:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    networks:
      custom-net:
        ipv4_address: 172.28.0.2
    depends_on:
      - zookeeper
    environment:
      - ZK_HOST=zookeeper
      - ZK_PORT=2181
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      custom-net:
        ipv4_address: 172.28.0.3
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg:Z
      - ./data/zookeeper:/data
      - ./data/datalog:/datalog
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  custom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
