// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/internal_service.proto

package internalserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBucketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketReq) Reset() {
	*x = CreateBucketReq{}
	mi := &file_proto_internal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketReq) ProtoMessage() {}

func (x *CreateBucketReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketReq.ProtoReflect.Descriptor instead.
func (*CreateBucketReq) Descriptor() ([]byte, []int) {
	return file_proto_internal_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateBucketReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CreateBucketResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResp) Reset() {
	*x = CreateBucketResp{}
	mi := &file_proto_internal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResp) ProtoMessage() {}

func (x *CreateBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResp.ProtoReflect.Descriptor instead.
func (*CreateBucketResp) Descriptor() ([]byte, []int) {
	return file_proto_internal_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBucketResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_internal_service_proto protoreflect.FileDescriptor

const file_proto_internal_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/internal_service.proto\x12\x0einternalserver\"?\n" +
	"\x0fCreateBucketReq\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\",\n" +
	"\x10CreateBucketResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2d\n" +
	"\x0fInternalService\x12Q\n" +
	"\fCreateBucket\x12\x1f.internalserver.CreateBucketReq\x1a .internalserver.CreateBucketRespB(Z&./server/internal/proto;internalserverb\x06proto3"

var (
	file_proto_internal_service_proto_rawDescOnce sync.Once
	file_proto_internal_service_proto_rawDescData []byte
)

func file_proto_internal_service_proto_rawDescGZIP() []byte {
	file_proto_internal_service_proto_rawDescOnce.Do(func() {
		file_proto_internal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_internal_service_proto_rawDesc), len(file_proto_internal_service_proto_rawDesc)))
	})
	return file_proto_internal_service_proto_rawDescData
}

var file_proto_internal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_internal_service_proto_goTypes = []any{
	(*CreateBucketReq)(nil),  // 0: internalserver.CreateBucketReq
	(*CreateBucketResp)(nil), // 1: internalserver.CreateBucketResp
}
var file_proto_internal_service_proto_depIdxs = []int32{
	0, // 0: internalserver.InternalService.CreateBucket:input_type -> internalserver.CreateBucketReq
	1, // 1: internalserver.InternalService.CreateBucket:output_type -> internalserver.CreateBucketResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_internal_service_proto_init() }
func file_proto_internal_service_proto_init() {
	if File_proto_internal_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_internal_service_proto_rawDesc), len(file_proto_internal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_service_proto_goTypes,
		DependencyIndexes: file_proto_internal_service_proto_depIdxs,
		MessageInfos:      file_proto_internal_service_proto_msgTypes,
	}.Build()
	File_proto_internal_service_proto = out.File
	file_proto_internal_service_proto_goTypes = nil
	file_proto_internal_service_proto_depIdxs = nil
}
