// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/exposed_broker_server.proto

package brokerserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBucketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketReq) Reset() {
	*x = CreateBucketReq{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketReq) ProtoMessage() {}

func (x *CreateBucketReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketReq.ProtoReflect.Descriptor instead.
func (*CreateBucketReq) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateBucketReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CreateBucketResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResp) Reset() {
	*x = CreateBucketResp{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResp) ProtoMessage() {}

func (x *CreateBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResp.ProtoReflect.Descriptor instead.
func (*CreateBucketResp) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBucketResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProducerConnectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProducerConnectionReq) Reset() {
	*x = GetProducerConnectionReq{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProducerConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProducerConnectionReq) ProtoMessage() {}

func (x *GetProducerConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProducerConnectionReq.ProtoReflect.Descriptor instead.
func (*GetProducerConnectionReq) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetProducerConnectionReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetProducerConnectionReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type GetProducerConnectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProducerConnectionResp) Reset() {
	*x = GetProducerConnectionResp{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProducerConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProducerConnectionResp) ProtoMessage() {}

func (x *GetProducerConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProducerConnectionResp.ProtoReflect.Descriptor instead.
func (*GetProducerConnectionResp) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetProducerConnectionResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetProducerConnectionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetConsumerConnnectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerConnnectionReq) Reset() {
	*x = GetConsumerConnnectionReq{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerConnnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerConnnectionReq) ProtoMessage() {}

func (x *GetConsumerConnnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerConnnectionReq.ProtoReflect.Descriptor instead.
func (*GetConsumerConnnectionReq) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetConsumerConnnectionReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetConsumerConnnectionReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type GetConsumerConnectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerConnectionResp) Reset() {
	*x = GetConsumerConnectionResp{}
	mi := &file_proto_exposed_broker_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerConnectionResp) ProtoMessage() {}

func (x *GetConsumerConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exposed_broker_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerConnectionResp.ProtoReflect.Descriptor instead.
func (*GetConsumerConnectionResp) Descriptor() ([]byte, []int) {
	return file_proto_exposed_broker_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetConsumerConnectionResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetConsumerConnectionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_exposed_broker_server_proto protoreflect.FileDescriptor

var file_proto_exposed_broker_server_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x48, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x4f, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x49, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x4f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xb3, 0x02, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x69, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x25, 0x5a,
	0x23, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_exposed_broker_server_proto_rawDescOnce sync.Once
	file_proto_exposed_broker_server_proto_rawDescData []byte
)

func file_proto_exposed_broker_server_proto_rawDescGZIP() []byte {
	file_proto_exposed_broker_server_proto_rawDescOnce.Do(func() {
		file_proto_exposed_broker_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exposed_broker_server_proto_rawDesc), len(file_proto_exposed_broker_server_proto_rawDesc)))
	})
	return file_proto_exposed_broker_server_proto_rawDescData
}

var file_proto_exposed_broker_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_exposed_broker_server_proto_goTypes = []any{
	(*CreateBucketReq)(nil),           // 0: brokerserver.CreateBucketReq
	(*CreateBucketResp)(nil),          // 1: brokerserver.CreateBucketResp
	(*GetProducerConnectionReq)(nil),  // 2: brokerserver.GetProducerConnectionReq
	(*GetProducerConnectionResp)(nil), // 3: brokerserver.GetProducerConnectionResp
	(*GetConsumerConnnectionReq)(nil), // 4: brokerserver.GetConsumerConnnectionReq
	(*GetConsumerConnectionResp)(nil), // 5: brokerserver.GetConsumerConnectionResp
}
var file_proto_exposed_broker_server_proto_depIdxs = []int32{
	0, // 0: brokerserver.BrokerService.CreateBucket:input_type -> brokerserver.CreateBucketReq
	2, // 1: brokerserver.BrokerService.GetProducerConnection:input_type -> brokerserver.GetProducerConnectionReq
	4, // 2: brokerserver.BrokerService.GetConsumerConnection:input_type -> brokerserver.GetConsumerConnnectionReq
	1, // 3: brokerserver.BrokerService.CreateBucket:output_type -> brokerserver.CreateBucketResp
	3, // 4: brokerserver.BrokerService.GetProducerConnection:output_type -> brokerserver.GetProducerConnectionResp
	5, // 5: brokerserver.BrokerService.GetConsumerConnection:output_type -> brokerserver.GetConsumerConnectionResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exposed_broker_server_proto_init() }
func file_proto_exposed_broker_server_proto_init() {
	if File_proto_exposed_broker_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exposed_broker_server_proto_rawDesc), len(file_proto_exposed_broker_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exposed_broker_server_proto_goTypes,
		DependencyIndexes: file_proto_exposed_broker_server_proto_depIdxs,
		MessageInfos:      file_proto_exposed_broker_server_proto_msgTypes,
	}.Build()
	File_proto_exposed_broker_server_proto = out.File
	file_proto_exposed_broker_server_proto_goTypes = nil
	file_proto_exposed_broker_server_proto_depIdxs = nil
}
