name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, reopened ]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    services:
      third-party-service:
        image: your-third-party-image
        ports:
          - 1234:1234  # Modify according to your service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.test.yml up -d

      - name: Wait for services to be ready
        run: sleep 10  

      - name: Run Tests
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic -gcflags=-l

      - name: Stop Docker Compose
        run: docker compose -f docker-compose.test.yml down
